### ISSUE TITLE
[TODO] Add getting started resources for new hackers

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethberlinzwei/KnowledgeBase#14]
In the main readme and/or hackers.md file we need to add resources for people new to Ethereum/Solidity/Web3 development.

This will be somewhat subjective and opinionated, and we all likely have ideas, but let's make a start and handle the complete consolidation when merging the PR, likely easier to all work in the same branch, whoever starts the PR first.

**Comment by ChrisChinchilla** [comment]
Started here https://github.com/ethberlinzwei/KnowledgeBase/pull/27

**Comment by soc1c** [comment]
continued in #37

**Comment by soc1c** [comment]
also link everything that's in `./resources`

**Comment by ChrisChinchilla** [comment]
Added more in #51
