### ISSUE TITLE
[TODO] Tarots of Tech mention

### ISSUE THREAD

**Issue by ChrisChinchilla** [ethberlinzwei/KnowledgeBase#25]

**Comment by ligi** [comment]
http://tarotcardsoftech.artefactgroup.com

name might be a hurdle for some - but it is good so projects can check if what they are building should be build.

![image](https://user-images.githubusercontent.com/111600/62537428-a7958800-b850-11e9-9b30-4bbe7b001c86.png)

**Comment by Joshfairhead** [comment]
Reminds me of ethicalOs.org - probably another one to remind people about!

**Comment by ligi** [comment]
yes - I think I even was hearing about these cards in a talk that was mainly about ethicalOs. 
Btw.: gave some cards to @franzihei - so they will be on site. But for mentioning in the knowledgebase we need to know where people can find it on site.

**Comment by Joshfairhead** [comment]
Ooooohhhhhh I'd love a deck for liminal village.com if possible!

**Comment by ligi** [comment]
unfortunately there is only one deck.I laminated them by hand - was quite some work - so I could only do one. Perhaps next year we can produce some cards with a professional producer and hand out decks. Unfortunately this did not work out this year and I went with the backup solution as I think it is important that projects get looked at with this tool.

**Comment by Joshfairhead** [comment]
Ok too bad, it looks like a great artifact and we'd love a copy. Is there a
downloadable DIY kit perhaps? Getting a crew to cut them out and laminate
sounds like a way for people to really ingrain them through physicality :)

**Comment by franzihei** [comment]
I'd say we can best put them at one of the help desks **or** is there maybe a designated area where hackers can meet mentors? Then I'd put them there.

**Comment by ligi** [comment]
sounds great. I think help desk is a good idea and easy to find.

**Comment by Joshfairhead** [comment]
Maybe spread them out around the place so people that are curious can go
searching?

Great way to meet people!

**Comment by franzihei** [comment]
Erm @soc1c there isn't only **one** help desk so we'd need to specify. My folks and possibly me at some point will be at the Layer 2 helpdesk so that would make sense I guess.

**Comment by soc1c** [comment]
Let's order more decks!

**Comment by ligi** [comment]
I could produce like 2 more decks - but my printer has problems currently. If anyone could print the deck I can do the lamination. Brought 100 lamination sleeves - and just used 30 so far

**Comment by soc1c** [comment]
No worries, I'm on it.
