### ISSUE TITLE
parity light.js repo moved

### ISSUE THREAD

**Issue by adamschmideg** [ethberlinzwei/KnowledgeBase#66]
Link in https://github.com/ethberlinzwei/KnowledgeBase/blob/master/resources.md#other-resources should be fixed.
https://github.com/parity-js/light.js is outdated, the new repo is at https://github.com/paritytech/js-libs

**Comment by ligi** [comment]
thanks for pointing out the 404 - but not sure if the new repo is correct - maybe @Tbaut can help here?
