### ISSUE TITLE
Workshops information

### ISSUE THREAD

**Issue by elpiel** [ethberlinzwei/KnowledgeBase#82]
Hello,
I couldn't find any information about what the workshops at Friday will consist. Any descriptions of the workshops, required tools (aka Laptops?!) and etc.

**Comment by ChrisChinchilla** [comment]
@elpiel Whole schedule is here - https://github.com/ethberlinzwei/KnowledgeBase/blob/master/the-event.md#hackathon-schedule

When it comes to prerequisites, we're not that sure, I'd say laptop, and installing core tools from the project won't hurt.

**Comment by elpiel** [comment]
Yeah, I saw that, but usually there is a description of what it is going to be covered/done. How should I choose which workshop I want to attend if I only have the title of it?

"IPFS workshop" for example.

**Comment by ChrisChinchilla** [comment]
@elpiel Unfortunately that's mostly the details we have from the hosts, but it's a good point and I'll ask…
